export const authStyles = {
  shell: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    minHeight: "100dvh",
    paddingBottom: 0,
  },
  logoWrap: {
    textAlign: "center",
    marginBottom: 32,
  },
  logoCircle: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 56,
    height: 56,
    borderRadius: 18,
    background: "var(--surface)",
    fontSize: 26,
    marginBottom: 14,
  },
  appName: {
    fontSize: 22,
    fontWeight: 700,
  },
  tagline: {
    color: "var(--text-muted)",
    fontSize: 13.5,
    marginTop: 6,
  },
  form: {
    padding: "0 24px",
    display: "flex",
    flexDirection: "column",
  },
  title: {
    fontSize: 19,
    fontWeight: 700,
    marginBottom: 18,
  },
  label: {
    fontSize: 13,
    color: "var(--text-muted)",
    fontWeight: 600,
    marginBottom: 8,
    marginTop: 4,
  },
  input: {
    background: "var(--surface)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-sm)",
    padding: "13px 14px",
    color: "var(--text)",
    fontSize: 14.5,
    marginBottom: 18,
    outline: "none",
  },
  submitBtn: {
    marginTop: 6,
    background: "var(--gold)",
    color: "#1A1200",
    border: "none",
    borderRadius: "var(--radius-md)",
    padding: "16px 0",
    fontSize: 15.5,
    fontWeight: 700,
  },
  error: {
    background: "var(--expense-soft)",
    color: "var(--expense)",
    borderRadius: "var(--radius-sm)",
    padding: "10px 12px",
    fontSize: 13,
    marginBottom: 16,
  },
  switchText: {
    textAlign: "center",
    color: "var(--text-muted)",
    fontSize: 13.5,
    marginTop: 20,
  },
  link: {
    color: "var(--gold)",
    fontWeight: 600,
    textDecoration: "none",
  },
};
